function shoutWhatsUpDawg(n) {
    for (let i = 0; i < n; i++){
        console.log("whats up dawg?!");
    }
    for (let i = 0; i < n; i++) {
        console.log("whats up dawg?!");
    }
}
shoutWhatsUpDawg(1000);
 
// -------------------------------------------------

function shoutWhatsUpDawg(n) {
    for (let i = 0; i < 4; i++) {
        console.log("whats up dawg?!");
    }
}
shoutWhatsUpDawg(1000);